Add database
MrOlegBar/java-filmorate pull request #1
Opened 2023-01-04 19:33 UTC by MrOlegBar

2023-01-05 19:51 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User postUser(@RequestBody @Valid User user) throws UserNotFoundException, FriendNotFoundException {
Если отправить неверный запрос на создания пользователя, то возвращается не очень понятное сообщение об ошибке
{
	"name2":"nameItem",
	"email":"email3email.com",
  "login":"login"
}

400
{
	"error": "must not be null"
}

2023-01-05 19:59 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/UserDbStorage.java
> +                    jdbcTemplate.update(sqlQueryForUpdateFriends, user.getId(), friendId, status);
Попробуй во всех местах, где в for вызывается какой-то запрос к базе, сделать эти запросы через batch
https://www.baeldung.com/spring-jdbc-batch-inserts
Это позволит сократить время работы с базой данных.
замечание по желанию

2023-01-05 20:02 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/MapRowToObject.java
> +            String sqlQueryForGenres = "SELECT * FROM FILMS_GENRES_VIEW WHERE FILM_ID = ?";
Все-таки это маппер. Получается он еще берет на себя функцию обращения к базе данных, что не совсем соответствует его назначению и нарушается принцип high cohesion.
Лучше сделать один запрос к базе данных, чем три.

2023-01-05 20:04 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/MapRowToObject.java
> +    public RatingMpa mapRowToRatingMpa(ResultSet resultSet, int rowNum) throws SQLException
параметр rowNum не используется

2023-01-05 20:20 UTC, EvgenyKoptubenko commented on src/test/java/ru/yandex/practicum/filmorate/storage/impl/dao/FilmDbStorageTests.java
> +    void contextLoads() {
Для чего в каждом тесте этот тест? Если он нужен, может быть его вынести тогда в базовый класс, раз он есть у всех классов

2023-01-05 20:23 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть замечания из разряда можно лучше

2023-01-06 12:17 UTC, MrOlegBar commented on src/test/java/ru/yandex/practicum/filmorate/storage/impl/dao/FilmDbStorageTests.java
> +    void contextLoads() {
Метод из прошлого)вроде проверяет подключения к контексту тестового класса. Вообщем-то не нужен конечно.

2023-01-06 12:31 UTC, MrOlegBar commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/MapRowToObject.java
> +    public RatingMpa mapRowToRatingMpa(ResultSet resultSet, int rowNum) throws SQLException
Видел и удалял, но удалял вместе с romNum в методе "mapRow(ResultSet rs, int rowNum)" и от этого было еще больше ошибок. Сейчас удалил только там, где просят)

2023-01-06 16:40 UTC, MrOlegBar commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public User postUser(@RequestBody @Valid User user) throws UserNotFoundException, FriendNotFoundException {
Действительно, добавил ограничение и не добавил текст в случае ошибки. Исправил.

2023-01-06 20:43 UTC, MrOlegBar commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/MapRowToObject.java
> +            String sqlQueryForGenres = "SELECT * FROM FILMS_GENRES_VIEW WHERE FILM_ID = ?";
Не смог ничего лучше придумать, как просто вынести лишние запросы в отдельные методы.

2023-01-08 18:07 UTC, MrOlegBar commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/dao/UserDbStorage.java
> +                    jdbcTemplate.update(sqlQueryForUpdateFriends, user.getId(), friendId, status);
Я что-то сделал)Вроде работает. Помогла информация отсюда https://docs.spring.io/spring-framework/docs/3.0.0.M4/reference/html/ch12s04.html

2023-01-08 20:53 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо

2023-01-13 16:50 UTC, merged